# Generated by Django 4.2.13 on 2024-07-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_about_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
